<?php

function h5p_math_input_h5p_scripts_alter(&$scripts, $libraries, $mode) {
  if ($mode == 'editor') {
    $scripts []= (object) [
      'path' => drupal_get_path('module', 'h5p_math_input') . '/vendor/ckplugin.js',
      'version' => '?v=1.0.21'
    ];
  }
}

function h5p_math_input_h5p_semantics_alter(&$semantics, $machine_name, $major_version = null, $minor_version = null) {
  foreach ($semantics as $object) {
    _h5p_math_input_recurse_h5p_semantics_object($object);
  }
}

function _h5p_math_input_recurse_h5p_semantics_object($object) {
  if (isset($object->type) && $object->type == 'text' && isset($object->widget) && $object->widget == 'html') {
    array_push($object->tags, 'eqneditor');
  }
  else if (isset($object->field)) {
    $field = $object->field;
    _h5p_math_input_recurse_h5p_semantics_object($field);
  }
  else if (isset($object->fields)) {
    $fields = $object->fields;
    foreach ($fields as $field) {
      _h5p_math_input_recurse_h5p_semantics_object($field);
    }
  }
}