<?php

function h5p_math_input_h5p_scripts_alter(&$scripts, $libraries, $mode) {
  if ($mode == 'editor') {
    $scripts []= (object) [
      'path' => drupal_get_path('module', 'h5p_math_input') . '/vendor/ckplugin.js',
      'version' => '?v=1.0.21'
    ];
  }
}

function h5p_math_input_h5p_semantics_alter(&$semantics, $machine_name, $major_version = null, $minor_version = null) {
  foreach ($semantics as $object) {
    h5p_math_input_recurse_h5p_semantics_object($object);
  }
}

function h5p_math_input_recurse_h5p_semantics_object($object) {
  if ($object->type == 'text' && $object->widget == 'html') {
    array_push($object->tags, 'eqneditor');
  }
  else if ($field = $object->field) {
    h5p_math_input_recurse_h5p_semantics_object($field);
  }
  else if ($fields = $object->fields) {
    foreach ($fields as $field) {
      h5p_math_input_recurse_h5p_semantics_object($field);
    }
  }
}